---
- name: Deploy common actions
  include_tasks: common_actions.yml

- name: Save secret credentials
  include_tasks: save_secret_credentials.yml

- name: Deploy files
  include_tasks: deploy_files.yml

- name: Deploy agent
  include_tasks: deploy_agent.yml
  when: deploy_agent_enabled | bool

- name: Deploy systemd service
  include_tasks: systemd_service.yml
