---
- name: Create credentials directories
  file:
    name: "{{ item }}"
    state: directory
    mode: 0600
  with_items:
    - "{{ deploy_home_directory }}/.almalinux-debranding-slack"
    - "{{ deploy_home_directory }}/.cas"

- name: Save Slack token
  template:
    src: "slack_token.yaml.j2"
    dest: "{{ deploy_home_directory }}/.almalinux-debranding-slack/token"
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Save cas credentials
  template:
    src: "cas_credentials.yaml.j2"
    dest: "{{ deploy_home_directory }}/.cas/credentials"
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Save ssh private key
  template:
    src: "ssh_key.j2"
    dest: "{{ deploy_home_directory }}/.ssh/id_rsa"
    owner: root
    group: root
    mode: 0600
    force: yes
  
- name: Save ssh public key
  template:
    src: "ssh_key.pub.j2"
    dest: "{{ deploy_home_directory }}/.ssh/id_rsa.pub"
    owner: root
    group: root
    mode: 0600
    force: yes
