#SPDX-License-Identifier: MIT-0
---
# defaults file for deploy

deploy_home_directory: "/root"
deploy_source_path: "{{ deploy_home_directory }}/autopatch-tool"
deploy_python_packages:
  - PyYAML==6.0.1
  - flask[async]==2.3.2
  - werkzeug==2.3.4
  - requests==2.32.3
  - slack_sdk==3.34.0
  - gunicorn==20.1.0

  - requests>=2.20.0
  - cyclonedx-python-lib==2.7.1
  - spdx-tools==0.8
  - urllib3<2.0
  - packageurl-python==0.10.3
  - GitPython==3.1.29
  - git+https://github.com/AlmaLinux/immudb-wrapper.git@0.1.5#egg=immudb_wrapper
  - googleapis-common-protos==1.66.0

deploy_dnf_packages:
  - python3
  - python3-pip
  - python3-rpm
  - python3-devel
  - python3-protobuf
  - git
  - /usr/bin/docker
  - rpm-build

deploy_gunicorn_port: 80

deploy_systemd_services:
  almalinux-autopatch.service: restarted

deploy_systemd_dir: "/usr/lib/systemd/system"
